name: Context
on: [push]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: check boolean
        run: echo ${{ contains( 'hello' , 'll' ) }}
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Dump Github Context 
      env: 
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"