name: Context
on: [push]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: check boolean
        run: echo ${{ contains( 'hello' , 'll' ) }}
  one:
    runs-on: ubuntu-latest
    needs: ["function"]
    if: github.event_name == 'push'
    steps:
    - name: Dump Github Context 
      env: 
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Before failure
      run: echo "Before Failure"
    - name: Failure
      run: eccho "failure"
    - name: After Failure
    #  if: failure()
      run: echo "After failure"
    - name: Always
      if: always()
      run: echo "VIVEK"