name: Data center

on:
  workflow_dispatch:
    inputs:
      k8_version:
        type: choice
        description: "Select k8 Version"
        required: true
        options:
          - v1.22.5
          - v1.21.5
      owner:
        type: string
        description: "Owner Name"
        required: true
      Cluster_name: 
        type: string
        description: "cluster Name"
        required: true
      master_config: 
        type: string 
        description: "Master node configurations"
        required: false
      worker_config:
        type: string
        description: "Worker node configurations"
        required: false

      datastore: 
        type: choice
        description: "Datastore"
        required: true
        options:
        - datastore1
        - datastore2
        - datastore3
        - datastore4
        - datastore5
        - datastore6
        - datastore7
      datacenter:
        type: choice
        description: "Data center"
        required: true
        options:
          - "datacenter-1"
          - "datacenter-2"
          - "datacenter-3"
jobs:
  ProvisionKubernetesCluster:
    runs-on: ubuntu-latest
    steps:
    - name: Create varibales.tfvars file
      run: |
        worker_config="${{ inputs.worker_config }}"
        IFS="," read -a myarray <<< $worker_config
        echo "${myarray[0]}"
        echo "${myarray[1]}"
        echo "${myarray[2]}"
        echo "${myarray[3]}"
        echo "Number of elements in the array: ${#myarray[@]}"