name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      k8_version:
        type: choice
        description: "Select k8 Version"
        required: true
        options:
          - v1.22.5
          - v1.21.5
       

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.k8_version }}"
