name: Matrix
on: [ push ]
jobs:
  nodeVersion:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: log node version
        run: node -v 

          
