on:
  workflow_dispatch:
    inputs:
      Kubeslice_Controller:
        description: 'Kubeslice Controller'
        required: true 
        type: boolean
      Kubeslice_Woker:
        description: 'Kubeslice Worker'
        required: true 
        type: boolean 

jobs:
  update-worker-to-rancher-partner-chart:
    if:  ${{ inputs.Kubeslice_Woker }} 
    runs-on: ubuntu-latest
    steps:
      - name: Worker
        run: echo ${{ inputs.Kubeslice_Woker }} 

  update-controller-to-rancher-partner-chart:
    if:  ${{ inputs.Kubeslice_Controller }}
    runs-on: ubuntu-latest
    steps:
      - name: Controller
        run: echo ${{ inputs.Kubeslice_Controller }}
  
