on:
  workflow_dispatch:
    inputs:
      Kubeslice_Controller:
        description: 'Kubeslice Controller'
        required: true 
        type: boolean
      Kubeslice_Woker:
        description: 'Kubeslice Worker'
        required: true 
        type: boolean 

jobs:
  update-charts-to-rancher-partner-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Worker
        if:  ${{ inputs.Kubeslice_Woker }} 
        run: echo ${{ inputs.Kubeslice_Woker }} 
      - name: Controller
        if:  ${{ inputs.Kubeslice_Controller }}
        run: echo ${{ inputs.Kubeslice_Woker }}